name: Push Main
on:
  push:
    branches:
        - main

jobs:
  master:
    runs-on: ubuntu-22.04
    name: Main Features
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Echo
        run: |
          echo "Running Push Main"