name: Scheduler
on:
  schedule:
    - cron: '0 * * * *'

jobs:
  master:
    runs-on: ubuntu-22.04
    name: Scheduler
    steps:
      - uses: actions/checkout@v4
        with:
          ref: coingecko
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
          branch: main
      - name: Update data
        run: |
          yarn install --immutable | grep -v 'YN0013'
          yarn data:update-price
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Scheduler
          author_email: scheduler@github.io
          message: 'Update data'
