name: Scheduler
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  master:
    runs-on: ubuntu-22.04
    name: Scheduler
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Echo
        run: |
          echo "Running Scheduler"